export type Feature = {
  key: string;
  icon: string;
  titleEn: string;
  titleSi: string;
  descEn: string;
  descSi: string;
  subEn: string[];
  subSi: string[];
  img: string;
  reverse: boolean;
};

export const features: Feature[] = [
  {
    key: 'student',
    icon: '👤',
    titleEn: 'Student Management',
    titleSi: 'ශිෂ්‍ය කළමනාකරණය',
    descEn: 'Student Management gives teachers one simple place to add and manage student profiles, track daily and monthly attendance, store parent and guardian contacts, generate progress reports, and manage class enrollments. Teachers can also view full student history in one place, making it easier to follow each student\'s learning journey. Each student profile can include a QR ID card for quick identification, and daily attendance can be marked as present, late, or absent.',
    descSi: 'ශිෂ්‍ය පැතිකඩ ඇතුළත් කිරීම, දෛනික සහ මාසික පැමිණීම, දෙමාපිය සම්බන්ධතා, ප්‍රගති වාර්තා සහ ලියාපදිංචිය.',
    subEn: ['Add and edit detailed student profiles', 'Track daily and monthly attendance', 'Store parent and guardian contact details', 'Generate student progress reports', 'Manage class enrollments', 'View full student history', 'Create student profiles, assign classes, and send join links', 'Share class join links by SMS or WhatsApp', 'Let students create accounts at student.easyclz.lk and join classes', 'Allow students to view marks, payment history, class notes, and chat with the subject teacher'],
    subSi: ['ශිෂ්‍ය පැතිකඩ ඇතුළත් කිරීම', 'දෛනික සහ මාසික පැමිණීම', 'දෙමාපිය සම්බන්ධතා ගබඩා කිරීම', 'ශිෂ්‍ය ප්‍රගති වාර්තා', 'ලියාපදිංචිය කළමනාකරණය', 'සම්පූර්ණ ශිෂ්‍ය ඉතිහාසය'],
    img: '/images/ai/1.png',
    reverse: false,
  },
  {
    key: 'payment',
    icon: '💳',
    titleEn: 'Payment Management',
    titleSi: 'ගෙවීම් කළමනාකරණය',
    descEn: 'Payment Management helps teachers and assistants collect payments through the app, define student fees when adding students, send payment SMS updates, and track class-by-class or full payment summaries in one place.',
    descSi: 'ගාස්තු ගෙවීම් වාර්තා කිරීම, ගෙවීම් ඉතිහාසය, කල් ඉකුත් ගෙවීම් අනතුරු ඇඟවීම්, ඉන්වොයිස් ජනනය.',
    subEn: ['Collect payments through the teacher app or assistant app', 'Set a standard amount, custom amount, or free-card option when adding a student', 'Send payment confirmation SMS messages to the registered mobile number', 'Send payment reminder SMS messages for overdue students', 'View payment summaries by class and across the full system', 'Filter students who did not pay last month and follow up quickly'],
    subSi: ['ගාස්තු ගෙවීම් වාර්තා කිරීම', 'ශිෂ්‍ය ගෙවීම් ඉතිහාසය', 'කල් ඉකුත් ගෙවීම් අනතුරු ඇඟවීම්', 'ඉන්වොයිස් ජනනය', 'බහු ගෙවීම් ක්‍රම', 'මාසික මූල්‍ය සාරාංශ'],
    img: '/images/ai/2.png',
    reverse: true,
  },
  {
    key: 'exam',
    icon: '📝',
    titleEn: 'Exam Monitoring',
    titleSi: 'විභාග අධීක්ෂණය',
    descEn: 'Exam Monitoring helps teachers create physical exams, save exam names, enter student marks one by one, generate reports, and publish results for students to view in the student portal.',
    descSi: 'විභාග සාදා නියම කිරීම, ශිෂ්‍ය ලකුණු ඇතුළු කිරීම, මුද්‍රිත ලකුණු පත්‍ර ජනනය, ශ්‍රේණිය විශ්ලේෂණය.',
    subEn: ['Create an exam and save the exam name, such as Mock Exam 001', 'Enter and edit marks for each student after the exam', 'Generate exam reports and printable mark sheets', 'Track student performance by exam and subject', 'Keep exam history and previous mark records in one place', 'Let students view their marks from the student portal'],
    subSi: ['විභාග සාදා නියම කිරීම', 'ශිෂ්‍ය ලකුණු ඇතුළු කිරීම', 'ලකුණු පත්‍ර ජනනය', 'ශ්‍රේණිය විශ්ලේෂණය', 'විෂය-වාරයේ කාර්ය සාධනය', 'විභාග ඉතිහාසය'],
    img: '/images/ai/3.png',
    reverse: false,
  },
  {
    key: 'online-exam',
    icon: '🖥️',
    titleEn: 'Online Exams (MCQ)',
    titleSi: 'මාර්ගගත විභාග (MCQ)',
    descEn: 'Online Exams let teachers build a question bank for each class, then publish a timed multiple-choice or true/false exam with a single join code. Students enter the code in the student portal, answer on their phones, and the app grades them instantly — no manual marking. If a student leaves the exam screen during the test (switches to another app or tab), they get a warning and the teacher sees how many times it happened, so you can tell who really did the exam on their own.',
    descSi: 'සෑම පන්තියකටම ප්‍රශ්න බැංකුවක් සාදා, කාල සීමාවක් සහිත MCQ / True-False විභාගයක් එක් කේතයක් සමඟ ප්‍රකාශයට පත් කරන්න. ශිෂ්‍යයන් කේතය ඇතුළත් කර දුරකථනයෙන් පිළිතුරු සපයන අතර, ස්වයංක්‍රීයව ලකුණු ලැබේ. ශිෂ්‍යයා විභාග තිරයෙන් ඉවත් වුවහොත් අනතුරු ඇඟවීමක් ලැබෙන අතර එය කී වරක් සිදුවූයේද යන්න ගුරුවරයාට පෙනේ.',
    subEn: ['Build a reusable question bank per class (MCQ and True/False)', 'Publish a timed exam from the bank with one join code', 'Choose how many questions and the time limit', 'Students take the exam in the student portal on any phone', 'Automatic instant marking — no manual grading', 'Anti-cheat: students are warned and flagged each time they leave the exam screen', 'See every student’s score and “left the screen” count in one place'],
    subSi: ['පන්තියකට නැවත භාවිත කළ හැකි ප්‍රශ්න බැංකුවක් සාදන්න (MCQ සහ True/False)', 'කේතයක් සමඟ කාල සීමා සහිත විභාගයක් ප්‍රකාශ කරන්න', 'ප්‍රශ්න ගණන සහ කාල සීමාව තෝරන්න', 'ශිෂ්‍යයන් ශිෂ්‍ය ද්වාරයෙන් ඕනෑම දුරකථනයකින් විභාගය කරයි', 'ස්වයංක්‍රීය ලකුණු කිරීම — අතින් ලකුණු කිරීමක් නැත', 'තිරයෙන් ඉවත් වන සෑම විටම අනතුරු ඇඟවීම සහ සලකුණු කිරීම', 'සෑම ශිෂ්‍යයෙකුගේම ලකුණු සහ “තිරයෙන් ඉවත් වූ වාර” ගණන එක තැනක'],
    img: '/images/ai/3.png',
    reverse: true,
  },
  {
    key: 'extra-class',
    icon: '📅',
    titleEn: 'Extra Classes',
    titleSi: 'අමතර පන්ති',
    descEn: 'Extra Classes let teachers and assistants run a one-off extra or revision session outside the regular monthly class. Each extra class has its own date, time, and location, and you decide how it is charged — make it free, charge the normal class fee, or set a custom amount, with free-card students kept free automatically. Mark who attended and collect payment for just that session, and every student is notified by SMS and in the class chat. Extra classes are kept completely separate from your monthly attendance and fees, so your regular reports are never affected.',
    descSi: 'සුපුරුදු මාසික පන්තියෙන් පිට එක්වරක් පවත්වන අමතර / පුනරීක්ෂණ සැසියක්. දිනය, වේලාව සහ ස්ථානය වෙන වෙනම තබා, නොමිලේ ද, සුපුරුදු ගාස්තුව ද, නැතහොත් custom මුදලක් ද ලෙස ගාස්තු තීරණය කරන්න. පැමිණි අය සලකුණු කර එම සැසියට පමණක් ගෙවීම එකතු කරන්න, සහ සෑම ශිෂ්‍යයෙකුටම SMS සහ class chat මගින් දැනුම් දේ.',
    subEn: ['Schedule a one-off extra or revision class with its own date, time, and location', 'Make it free, charge the normal class fee, or set a custom amount for that session', 'Free-card students automatically stay free for extra classes too', 'Mark attendance and collect payment for just that session', 'Kept separate from monthly attendance and fees — regular reports stay accurate', 'Every student is notified automatically by SMS and in the class chat', 'Assistants can run extra classes and collect payments as well'],
    subSi: ['දිනය, වේලාව, ස්ථානය සහිතව එක්වරක් අමතර / පුනරීක්ෂණ පන්තියක් සැකසීම', 'නොමිලේ, සුපුරුදු ගාස්තුව, හෝ custom මුදලක් ලෙස ගාස්තු කිරීම', 'free-card ශිෂ්‍යයන් අමතර පන්ති සඳහාද ස්වයංක්‍රීයව නොමිලේ', 'එම සැසියට පමණක් පැමිණීම සහ ගෙවීම', 'මාසික පැමිණීම් සහ ගාස්තු වලින් වෙන්ව තබයි', 'SMS සහ class chat මගින් ස්වයංක්‍රීය දැනුම්දීම', 'සහයකයන්ටද අමතර පන්ති පවත්වා ගෙවීම් එකතු කළ හැක'],
    img: '/images/ai/6.png',
    reverse: false,
  },
  {
    key: 'teacher-app',
    icon: '📱',
    titleEn: 'Teacher Mobile App',
    titleSi: 'ගුරු ජංගම යෙදවුම',
    descEn: 'Available on iOS and Android. Mark attendance offline, view full class schedule, and sync data when back online.',
    descSi: 'iOS සහ Android හි ලබා ගත හැකිය. ඕෆ්ලයින් ලෙස පැමිණීම සලකුණු කිරීම, සම්පූර්ණ කාලසටහන, ස්වයංක්‍රීය sync.',
    subEn: ['Available on iOS and Android', 'Mark attendance fully offline', 'View full class schedule', 'Sync data when back online', 'Push notifications for reminders', 'Quick access to student info'],
    subSi: ['iOS සහ Android හි ලබා ගත හැකිය', 'ඕෆ්ලයින් ලෙස පැමිණීම', 'සම්පූර්ණ කාලසටහන', 'නැවත සම්බන්ධ වූ විට sync', 'Push notifications', 'ශිෂ්‍ය ඉක්මන් ප්‍රවේශය'],
    img: '/images/ai/4.png',
    reverse: true,
  },
  {
    key: 'assistant-app',
    icon: '🧑‍💼',
    titleEn: 'Assistant App',
    titleSi: 'සහයක යෙදුම',
    descEn: 'As student numbers grow, teachers may need assistants to help manage daily class work. The Assistant App lets assistants support the teacher by collecting payments, marking student attendance, and handling student registrations through the app.',
    descSi: 'ශිෂ්‍ය සංඛ්‍යාව වැඩි වනවිට දෛනික පන්ති කටයුතු සඳහා සහයකයන් අවශ්‍ය විය හැක. සහයක යෙදුම හරහා ගෙවීම් එකතු කිරීම, පැමිණීම සලකුණු කිරීම සහ නව ශිෂ්‍ය ලියාපදිංචි කිරීම් කළ හැක.',
    subEn: ['Use assistants when teachers cannot manually handle every task', 'Collect payments through the assistant app', 'Mark student attendance quickly during class', 'Register new students through the app', 'Reduce the teacher’s workload as classes grow', 'Keep daily class operations organized with support staff'],
    subSi: ['සෑම වැඩක්ම ගුරුවරයාටම තනිව හසුරුවන්න අමාරු වනවිට සහයකයන් යොදවන්න', 'සහයක යෙදුම හරහා ගෙවීම් එකතු කරන්න', 'පන්තියේදී ශිෂ්‍ය පැමිණීම ඉක්මනින් සලකුණු කරන්න', 'නව ශිෂ්‍යයන් යෙදුම හරහා ලියාපදිංචි කරන්න', 'පන්ති වැඩි වනවිට ගුරුවරයාගේ වැඩබර අඩු කරන්න', 'සහය කාර්ය මණ්ඩලය සමඟ දෛනික පන්ති කටයුතු පිළිවෙලට තබාගන්න'],
    img: '/images/ai/5.png',
    reverse: false,
  },
  {
    key: 'attendance',
    icon: '✅',
    titleEn: 'Attendance',
    titleSi: 'පැමිණීම',
    descEn: 'Attendance lets teachers and assistants mark daily attendance easily. Assistants can scan QR codes for attendance and payment collection, while teachers can directly update today\'s attendance without QR. Both teacher and assistant attendance features also work offline.',
    descSi: 'පැමිණීම විශේෂාංගය ගුරුවරුන්ට සහ සහයකයන්ට දෛනික පැමිණීම පහසුවෙන් සලකුණු කිරීමට ඉඩ දෙයි. සහයකයන්ට QR scan මගින් පැමිණීම සහ ගෙවීම් එකතු කළ හැකි අතර, ගුරුවරුන්ට QR නොමැතිව අද පැමිණීම update කළ හැක.',
    subEn: ['Mark attendance from the teacher app or assistant app', 'Assistants can scan QR codes for attendance', 'Assistants can also use QR flow while collecting payments', 'Teachers can directly update today\'s attendance without QR scanning', 'Send SMS messages to the registered home number when a student is absent', 'Use attendance features offline for both teachers and assistants'],
    subSi: ['ගුරු යෙදුමෙන් හෝ සහයක යෙදුමෙන් පැමිණීම සලකුණු කරන්න', 'සහයකයන්ට QR scan මගින් පැමිණීම කළ හැක', 'ගෙවීම් එකතු කරන විටත් සහයකයන්ට QR ක්‍රමය භාවිතා කළ හැක', 'ගුරුවරුන්ට QR scan නොකරම අද පැමිණීම update කළ හැක', 'නොපැමිණි සිසුන්ගේ නිවසේ ලියාපදිංචි අංකයට SMS යවන්න', 'ගුරුවරුන්ටත් සහයකයන්ටත් offline ලෙස පැමිණීම භාවිතා කරන්න'],
    img: '/images/ai/6.png',
    reverse: true,
  },
  {
    key: 'reports',
    icon: '📊',
    titleEn: 'Reports & SMS',
    titleSi: 'වාර්තා සහ SMS',
    descEn: 'Reports & SMS helps teachers get full payment reports, unpaid student reports, exam reports, and attendance reports, while important actions can also send SMS updates to the registered number.',
    descSi: 'දෛනික, සතිපතා, මාසික වාර්තා. ශිෂ්‍යයන් සහ දෙමාපියන්ට ස්වයංක්‍රීය SMS.',
    subEn: ['Get full payment reports across classes', 'View unpaid student reports and follow up quickly', 'Generate exam reports and attendance reports', 'Send SMS messages for important actions to the registered mobile number', 'Send payment reminders and result notifications by SMS', 'Keep reporting and communication in one place'],
    subSi: ['මාසික පැමිණීම් වාර්තා', 'සවිස්තරාත්මක ගෙවීම් වාර්තා', 'ස්වයංක්‍රීය SMS මතක් කිරීම්', 'SMS ගෙවීම් නියමිත දිනය', 'විභාග ප්‍රතිඵල SMS', 'අපනයනය කළ හැකි වාර්තා'],
    img: '/images/ai/7.png',
    reverse: false,
  },
  {
    key: 'notes',
    icon: '📄',
    titleEn: 'Notes & Files',
    titleSi: 'සටහන් සහ ගොනු',
    descEn: 'Teachers can upload class notes, PDFs, and study materials directly from the teacher app. Students can then download and view those files from the student portal at any time, no need to share files through WhatsApp or separate apps.',
    descSi: 'ගුරුවරුන්ට ගුරු යෙදුමෙන් සටහන්, PDF සහ අධ්‍යයන ද්‍රව්‍ය upload කළ හැකිය. ශිෂ්‍යයන්ට ඕනෑම වෙලාවක ශිෂ්‍ය ද්වාරයෙන් download කළ හැකිය.',
    subEn: ['Upload notes, PDFs, and study files from the teacher app', 'Students download files directly from the student portal', 'No need to share files through WhatsApp or other apps', 'Files are organised by class and visible only to enrolled students', 'Teachers can update or remove files anytime', 'Keeps all class materials in one secure place'],
    subSi: ['ගුරු යෙදුමෙන් සටහන්, PDF upload කරන්න', 'ශිෂ්‍යයන් ශිෂ්‍ය ද්වාරයෙන් download කරයි', 'WhatsApp හෝ වෙනත් apps අවශ්‍ය නැත', 'පන්තිය අනුව ගොනු ගොනු කෙරේ', 'ගුරුවරුන්ට ගොනු ඕනෑ වෙලාවක update/remove කළ හැකිය', 'සියලු ද්‍රව්‍ය එක ආරක්ෂිත ස්ථානයක'],
    img: '/images/ai/8.png',
    reverse: false,
  },
  {
    key: 'chat',
    icon: '💬',
    titleEn: 'Teacher–Student Chat',
    titleSi: 'ගුරු–ශිෂ්‍ය කතාබස',
    descEn: 'Teachers can send announcements and messages to their class directly through the teacher app. Students see those messages in the student portal. Students can also reply so teachers and students can communicate without needing a separate chat app.',
    descSi: 'ගුරුවරුන්ට ගුරු යෙදුම හරහා කෙලින්ම class ට දැනුම්දීම් සහ messages යැවිය හැකිය. ශිෂ්‍යයන් ශිෂ්‍ය ද්වාරයෙන් ඒවා දකිනු ලැබේ.',
    subEn: ['Teachers send class announcements from the teacher app', 'Students receive and read messages in the student portal', 'Students can reply directly to teacher messages', 'No external chat app needed, communication is built in', 'Each class has its own separate chat thread', 'Keeps all class communication in one organised place'],
    subSi: ['ගුරු යෙදුමෙන් class announcements යවන්න', 'ශිෂ්‍යයන් ශිෂ්‍ය ද්වාරයෙන් messages කියවයි', 'ශිෂ්‍යයන්ට කෙලින්ම reply කළ හැකිය', 'external chat app අවශ්‍ය නැත', 'සෑම class එකකටම වෙනම chat thread', 'සියලු communication එක ස්ථානයක'],
    img: '/images/ai/9.png',
    reverse: true,
  },
  {
    key: 'portal',
    icon: '🎓',
    titleEn: 'Student Portal',
    titleSi: 'ශිෂ්‍ය ද්වාරය',
    descEn: 'Students create a free account at student.easyclz.lk, verify their phone number with an OTP, then join classes using the teacher\'s class code. From the portal students can view payments, exam marks, class notes, and chat with their teacher, all from mobile or web.',
    descSi: 'ශිෂ්‍යයන් student.easyclz.lk හිදී නොමිලේ account සාදා, OTP මගින් phone verify කොට, class code ඇතුළු කිරීමෙන් classes join කරයි.',
    subEn: ['Register at student.easyclz.lk and verify your phone number with an OTP', 'Join classes by entering the teacher\'s class code', 'View payment QR code and full payment history', 'Check exam marks and download class notes and files', 'Read and reply to teacher messages in the class chat', 'Works fully on mobile and web, no app download required'],
    subSi: ['student.easyclz.lk හිදී OTP verify කොට ලියාපදිංචි', 'Class code ඇතුළු කිරීමෙන් classes join', 'ගෙවීම් QR සහ ගෙවීම් ඉතිහාසය', 'විභාග ලකුණු සහ class notes download', 'Teacher messages කියවා reply කිරීම', 'Mobile සහ web, app download අවශ්‍ය නැත'],
    img: '/images/ai/10.png',
    reverse: false,
  },
];
