import { StyleSheet } from 'react-native';
import type { ThemeColors } from '../../../lib/theme/store';

/** Styles for the new-payment wizard. Extracted from new.tsx to keep the
 *  screen file focused on behaviour. Built per-theme from colors. */
export function buildStyles(colors: ThemeColors) {
  return StyleSheet.create({
    wizardBackRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingTop: 4 },
    wizardBack: { flexDirection: 'row', alignItems: 'center', height: 40, paddingHorizontal: 4 },

    scroll: { padding: 16, paddingBottom: 56 },

    errorBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.surface,
      padding: 12,
      borderRadius: 10,
      borderLeftWidth: 3,
      borderLeftColor: colors.danger,
      marginBottom: 12,
    },
    errorText: { fontSize: 13, flex: 1 },

    hint: { fontSize: 13, color: colors.textMuted, marginTop: 4, marginBottom: 8 },
    hintBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      marginBottom: 8,
    },

    labelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8, marginTop: 16 },
    sectionLabel: { fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8, marginTop: 16 },
    selectedCount: { fontSize: 12, fontWeight: '700' },

    chipRow: { flexDirection: 'row', flexWrap: 'wrap', marginBottom: 2 },
    chip: {
      paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999,
      borderWidth: 1, borderColor: colors.border, marginRight: 8, marginBottom: 8,
    },
    chipActive: { borderColor: colors.primary, backgroundColor: colors.primary },
    chipText: { fontSize: 13, color: colors.text },
    chipTextActive: { color: colors.primaryText, fontWeight: '600' },

    multiMonthBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      marginBottom: 4,
    },
    multiMonthText: { fontSize: 13 },

    skipNotice: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      padding: 12,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      marginBottom: 12,
    },
    skipNoticeText: { fontSize: 13, flex: 1, lineHeight: 18 },

    searchWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 44,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: 12,
      marginBottom: 8,
      gap: 8,
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    searchInput: { flex: 1, fontSize: 14 },

    studentList: {
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      overflow: 'hidden',
      marginBottom: 8,
    },
    studentRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      minHeight: 56,
    },
    studentRowName: { fontSize: 15, fontWeight: '600', marginBottom: 2 },
    studentRowCode: { fontSize: 12 },

    selectedCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1.5,
      borderColor: colors.primary,
      padding: 14,
      marginBottom: 4,
    },
    selectedAvatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectedAvatarText: { color: '#fff', fontSize: 16, fontWeight: '700' },
    selectedName: { fontSize: 15, fontWeight: '700', color: colors.text, marginBottom: 2 },
    selectedCode: { fontSize: 12, color: colors.textMuted, fontFamily: 'monospace' },
    selectedMeta: { fontSize: 12, color: colors.textMuted, marginTop: 2 },
    changeBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, borderWidth: 1 },
    changeBtnText: { fontSize: 13, fontWeight: '600' },

    allPaidBox: {
      borderRadius: 12,
      padding: 20,
      borderWidth: StyleSheet.hairlineWidth,
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    allPaidText: { fontSize: 14, textAlign: 'center', lineHeight: 20 },

    feeHint: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 4,
      marginBottom: 4,
      borderWidth: StyleSheet.hairlineWidth,
    },
    feeHintText: { fontSize: 13 },

    partialCard: {
      borderRadius: 12,
      borderWidth: 1.5,
      padding: 12,
      marginTop: 8,
      marginBottom: 4,
      gap: 0,
    },
    partialCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginBottom: 10,
    },
    partialCardTitle: { fontSize: 13, fontWeight: '700', color: '#d97706' },
    partialRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 5,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: '#fde68a',
    },
    partialRowLast: { borderBottomWidth: 0, paddingBottom: 8 },
    partialLabel: { fontSize: 13, color: '#78716c' },
    partialValue: { fontSize: 13, fontWeight: '600', color: '#1c1917' },
    partialCap: {
      fontSize: 11,
      color: '#b45309',
      fontWeight: '600',
      textAlign: 'center',
      paddingTop: 2,
    },

    totalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      marginTop: 8,
      marginBottom: 4,
    },

    input: {
      height: 48,
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      paddingHorizontal: 14,
      fontSize: 15,
    },

    saveBtn: {
      marginTop: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: colors.primary,
      borderRadius: 14,
      paddingVertical: 16,
      minHeight: 52,
    },
    saveBtnText: { color: colors.primaryText, fontSize: 16, fontWeight: '700' },

    confirmCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      marginBottom: 24,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    confirmTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 12 },
    confirmIconBox: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmTitle: { fontSize: 16, fontWeight: '700' },

    successCircle: {
      width: 96,
      height: 96,
      borderRadius: 48,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 16,
      marginBottom: 16,
    },
    successTitle: { fontSize: 36, fontWeight: '900', letterSpacing: -0.5 },
    successSub: { fontSize: 16, marginTop: 4, marginBottom: 24 },

    receiptCard: {
      width: '100%',
      borderRadius: 16,
      borderWidth: StyleSheet.hairlineWidth,
      padding: 16,
      marginBottom: 16,
    },

    doneBtns: { flexDirection: 'row', gap: 12, width: '100%', marginBottom: 8 },
    shareBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 14,
      borderRadius: 14,
      borderWidth: 1.5,
      minHeight: 52,
    },
    shareBtnText: { fontSize: 15, fontWeight: '700' },
    doneBtn: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 14,
      borderRadius: 14,
      minHeight: 52,
    },
    doneBtnText: { fontSize: 15, fontWeight: '700' },
  });
}
